services:
  backend:
    build:
      context: ./backend
    container_name: vipshop-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: vipshop-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: vipshop-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: vipshop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
