const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PAYMENT_NOT_VERIFIED: 'PAYMENT_NOT_VERIFIED',
  PAYMENT_ALREADY_USED: 'PAYMENT_ALREADY_USED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  INVENTORY_SNAPSHOT_MISSING: 'INVENTORY_SNAPSHOT_MISSING',
  ORDER_EMPTY: 'ORDER_EMPTY',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

const ERROR_TYPES = {
  USER: 'USER',
  BUSINESS: 'BUSINESS',
  SYSTEM: 'SYSTEM',
};

export { ERROR_CODES, ERROR_TYPES };
